### ISSUE TITLE
Send airline details to payment service provider

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-datatrans#6]
If an airline acts as a merchant they (=we) are obliged to send airline details in the payment transaction (or in a subsequent interaction).

Instructions from Datatrans (see also attached xml_settlement_airline_1.4.pdf):

In order to process airline properties you have to capture the authorized transactions according to our enhanced XML Settlement API for Airlines (see attachment). With the exception of the “uppTransactionId”, all shaded parameters are optional.

[xml_settlement_airline_1.4.pdf](https://github.com/VirtoCommerce/vc-module-datatrans/files/1836490/xml_settlement_airline_1.4.pdf)

**Comment by ksavosteev** [comment]
1. Install Virtocommerce.DatatransModule.Core nuget package
2. Register DatatransModule settlement observer, i.e
`_container.RegisterType<IObserver<DatatransBeforeCapturePaymentEvent>, DatatransObserver>("DatatransObserver");`
or in case of needing services in observer:
`_container.RegisterType<IObserver<DatatransBeforeCapturePaymentEvent>, DatatransObserver>("DatatransObserver", InjectionConstructor(_container.Resolve<YOURSERVIECE1>(), _container.Resolve<YOURSERVIECE2>()));`
3. in your observer in OnNext method assign event AirlineData property, i.e.
```
value.AirlineData = new DatatransAirlineData()
            {
                CountryCode = "US",
                AgentCode = "33992921",
                PNR = "ABCDEF",
                IssueDate = "20120910"
            };
            var ticket = new DatatransTicket()
            ....
```
This data will go to DT with Settlement request.
